// automatically generated by the FlatBuffers compiler, do not modify

package User

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type GetUserReq struct {
	_tab flatbuffers.Table
}

func GetRootAsGetUserReq(buf []byte, offset flatbuffers.UOffsetT) *GetUserReq {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &GetUserReq{}
	x.Init(buf, n+offset)
	return x
}

func (rcv *GetUserReq) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *GetUserReq) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *GetUserReq) Id() int32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.GetInt32(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *GetUserReq) MutateId(n int32) bool {
	return rcv._tab.MutateInt32Slot(4, n)
}

func GetUserReqStart(builder *flatbuffers.Builder) {
	builder.StartObject(1)
}
func GetUserReqAddId(builder *flatbuffers.Builder, id int32) {
	builder.PrependInt32Slot(0, id, 0)
}
func GetUserReqEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
