// automatically generated by the FlatBuffers compiler, do not modify

package Role

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type EmptyReq struct {
	_tab flatbuffers.Table
}

func GetRootAsEmptyReq(buf []byte, offset flatbuffers.UOffsetT) *EmptyReq {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &EmptyReq{}
	x.Init(buf, n+offset)
	return x
}

func (rcv *EmptyReq) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *EmptyReq) Table() flatbuffers.Table {
	return rcv._tab
}

func EmptyReqStart(builder *flatbuffers.Builder) {
	builder.StartObject(0)
}
func EmptyReqEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
