// automatically generated by the FlatBuffers compiler, do not modify

package Role

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type RoleResp struct {
	_tab flatbuffers.Table
}

func GetRootAsRoleResp(buf []byte, offset flatbuffers.UOffsetT) *RoleResp {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &RoleResp{}
	x.Init(buf, n+offset)
	return x
}

func (rcv *RoleResp) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *RoleResp) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *RoleResp) Roles(obj *Role, j int) bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		x := rcv._tab.Vector(o)
		x += flatbuffers.UOffsetT(j) * 4
		x = rcv._tab.Indirect(x)
		obj.Init(rcv._tab.Bytes, x)
		return true
	}
	return false
}

func (rcv *RoleResp) RolesLength() int {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.VectorLen(o)
	}
	return 0
}

func RoleRespStart(builder *flatbuffers.Builder) {
	builder.StartObject(1)
}
func RoleRespAddRoles(builder *flatbuffers.Builder, roles flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(roles), 0)
}
func RoleRespStartRolesVector(builder *flatbuffers.Builder, numElems int) flatbuffers.UOffsetT {
	return builder.StartVector(4, numElems, 4)
}
func RoleRespEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
