// automatically generated by the FlatBuffers compiler, do not modify

package Role

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type Role struct {
	_tab flatbuffers.Table
}

func GetRootAsRole(buf []byte, offset flatbuffers.UOffsetT) *Role {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &Role{}
	x.Init(buf, n+offset)
	return x
}

func (rcv *Role) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *Role) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *Role) Id() int32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.GetInt32(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *Role) MutateId(n int32) bool {
	return rcv._tab.MutateInt32Slot(4, n)
}

func (rcv *Role) Name() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func RoleStart(builder *flatbuffers.Builder) {
	builder.StartObject(2)
}
func RoleAddId(builder *flatbuffers.Builder, id int32) {
	builder.PrependInt32Slot(0, id, 0)
}
func RoleAddName(builder *flatbuffers.Builder, name flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(1, flatbuffers.UOffsetT(name), 0)
}
func RoleEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
